### ISSUE TITLE
LibraryLoader.java 

### ISSUE THREAD

**Issue by radityagumay** [CleverTap/clevertap-android-sdk#10]
```
Caused by java.lang.UnsatisfiedLinkError: dlopen failed: "/system/app/Chrome/Chrome.apk!/lib/armeabi-v7a/libmonochrome.so" is 32-bit instead of 64-bit
       at java.lang.Runtime.loadLibrary0(Runtime.java:989)
       at java.lang.System.loadLibrary(System.java:1562)
       at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:89)
       at org.chromium.base.library_loader.LibraryLoader.loadNowOverrideApplicationContext(LibraryLoader.java:35)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.I(WebViewChromiumFactoryProvider.java:61)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.(WebViewChromiumFactoryProvider.java:31)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198)
       at android.webkit.WebView.getFactory(WebView.java:2347)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2342)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2401)
       at android.view.View.(View.java:4029)
       at android.view.View.(View.java:4154)
       at android.view.ViewGroup.(ViewGroup.java:579)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java:55)
       at android.webkit.WebView.(WebView.java:627)
       at android.webkit.WebView.(WebView.java:572)
       at android.webkit.WebView.(WebView.java:555)
       at com.gojek.life.component.widget.LifeWebView.(LifeWebView.kt:11)
       at com.gojek.life.component.widget.LifeWebView.(LifeWebView.kt:10)
       at com.gojek.life.component.widget.LifeWebView.(LifeWebView.kt)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
       at com.gojek.golife.presentation.feature.base.fragment.LifeBaseViewFragment.onCreateView(LifeBaseViewFragment.kt:10)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6228)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

got this issue from fabric.

happens on XIAOMI REDMI 4X and REDMI NOTE 4.
usage SDK Version : 3.1.7

**Comment by darshanclevertap** [comment]
@radityagumay Could you explain how is this caused by the CleverTap Android SDK? Nothing in the stack trace points to any of the CleverTap SDK files. Also, version 3.1.7 is quite old now, I would suggest you update to 3.1.10

**Comment by mwshubham** [comment]
Agree with @darshanclevertap This is not related to CleverTap. I have got this issue recently. I am currently investigating it. @radityagumay Do you have anything to share on this?


![1](https://user-images.githubusercontent.com/29930308/98228350-7c7f7400-1f7e-11eb-93f8-82ad6a5ccc5c.png)
