### ISSUE TITLE
Possible ANR onInstallReferrerSetupFinished (Called on Main Thread)

### ISSUE THREAD

**Issue by mwshubham** [CleverTap/clevertap-android-sdk#106]
```
Caused by com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:811)
       at com.google.android.a.a.a(a.java:4)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.a(IGetInstallReferrerService.java:4)
       at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:8)
       at com.clevertap.android.sdk.CleverTapAPI$45.onInstallReferrerSetupFinished(CleverTapAPI.java:6730)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:5)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1691)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1720)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
```

Dependency: api 'com.clevertap.android:clevertap-android-sdk:3.8.2'

**Comment by piyush-kukadiya** [comment]
@mwshubham Does `anrwatchdog` reported stack trace for single thread only? which you posted above or there are multiple stack trace? If there are multiple then please post whole stack trace to get details of each thread.

**Comment by mwshubham** [comment]
I am not sure Firebase Crashlytics support logging multiple stack trace using [recordException](https://firebase.google.com/docs/reference/android/com/google/firebase/crashlytics/FirebaseCrashlytics#public-void-recordexception-throwable-throwable)

On investigating, we found out we are using [@AddTrace](https://firebase.google.com/docs/reference/android/com/google/firebase/perf/metrics/AddTrace) on [onInstallReferrerSetupFinished](https://developer.android.com/reference/com/android/installreferrer/api/InstallReferrerStateListener#oninstallreferrersetupfinished) which could also be blocking the main thread. 

I am assuming there is no recent change in `com.clevertap.android.sdk.CleverTapAPI$45.onInstallReferrerSetupFinished` which might lead to this ANR. Please mark this hold/closed.

**Comment by piyush-kukadiya** [comment]
@mwshubham
```
at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:8)
       at com.clevertap.android.sdk.CleverTapAPI$45.onInstallReferrerSetupFinished(CleverTapAPI.java:6730)
```
 `onInstallReferrerSetupFinished` gets called on main thread and we are not doing any heavy operations in this callback, also `getInstallReferrer()` is a light weight synchronous call and safe to call on main thread. We are using [google docs](https://developer.android.com/reference/com/android/installreferrer/api/InstallReferrerClient#getinstallreferrer) as it is for google ad id integration

closing as of now.
