### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver com.clevertap.android.sdk.InstallReferrerBroadcastReceiver

### ISSUE THREAD

**Issue by Gaurav328** [CleverTap/clevertap-android-sdk#114]
Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver com.clevertap.android.sdk.InstallReferrerBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.InstallReferrerBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/base.apk", zip file "/data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.arm64_v8a.apk", zip file "/data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.en.apk", zip file "/data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/lib/arm64, /data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/base.apk!/lib/arm64-v8a, /data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4054)
       at android.app.ActivityThread.access$1700(ActivityThread.java:242)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2078)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7830)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)

Caused by java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.InstallReferrerBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/base.apk", zip file "/data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.arm64_v8a.apk", zip file "/data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.en.apk", zip file "/data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/lib/arm64, /data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/base.apk!/lib/arm64-v8a, /data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.viewlift.hoichoi-ZtNEBCIGIBof82p5zwZZtw==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
       at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4047)
       at android.app.ActivityThread.access$1700(ActivityThread.java:242)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2078)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7830)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)

**Comment by Gaurav328** [comment]
this is firebase crash log

**Comment by piyush-kukadiya** [comment]
@Gaurav328 Please check your **merged** manifest file. If you find `InstallReferrerBroadcastReceiver` in it then next step is to check from where is it getting merged.

1. If it's coming from your manifest then remove it.
2. Check what all cleverTap SDKs you are using, one of the old version of SDK might be using it, in that case update sdk version.

**Comment by Gaurav328** [comment]
<receiver
            android:name="com.clevertap.android.sdk.InstallReferrerBroadcastReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER"/>
            </intent-filter>
        </receiver>

**Comment by Gaurav328** [comment]
<receiver
            android:name="com.clevertap.android.sdk.InstallReferrerBroadcastReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER"/>
            </intent-filter>
        </receiver>

**Comment by Gaurav328** [comment]
<receiver 
android:name="com.clevertap.android.sdk.InstallReferrerBroadcastReceiver" 
android:exported="true"> 
<intent-filter> 
<action android:name="com.android.vending.INSTALL_REFERRER"/> 
</intentfilter> 
</receiver>

**Comment by Gaurav328** [comment]
we are using InstallReferrerBroadcastReceiver

**Comment by darshanclevertap** [comment]
@Gaurav328 Using the `InstallReferrerBroadcastReceiver` was deprecated in January 2020 release. Could you please remove it from the manifest? That will stop showing up the crash on your Crashlytics
