### ISSUE TITLE
Xioami push service causing crahes

### ISSUE THREAD

**Issue by LonelyCpp** [CleverTap/clevertap-android-sdk#122]
We recently integrated xiaomi's push notifications through clevertap with

`com.clevertap.android:clevertap-xiaomi-sdk:1.0.0`

We started noticing random crashes from this pushservice - 

```
FATAL EXCEPTION: main
Process: com.app.android:pushservice, PID: 18726
java.lang.RuntimeException: Unable to create application com.app.android.MainApplication: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
...
```

**Comment by darshanclevertap** [comment]
@LonelyCpp The extra details help a lot. Can you share the entire stack trace from the crash as well?

**Comment by LonelyCpp** [comment]
sure
```
FATAL EXCEPTION: main
Process: com.smallcase.android:pushservice, PID: 18726
java.lang.RuntimeException: Unable to create application com.smallcase.android.MainApplication: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
	at org.chromium.android_webview.AwBrowserProcess.a(PG:40)
	at vo.c(PG:88)
	at vo.b(PG:152)
	at vo.e(PG:169)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:211)
	at android.webkit.WebView.setWebContentsDebuggingEnabled(WebView.java:1861)
	at com.smallcase.android.MainApplication.onCreate(MainApplication.java:7)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
	... 8 more
```

here's a video of the behaviour - https://kapwi.ng/c/az0CZkA5

**Comment by piyush-kukadiya** [comment]
@LonelyCpp Can you help with reproducing this, I have added `com.clevertap.android:clevertap-xiaomi-sdk:1.0.0` in Starter app but App is launching successfully without a crash.

Transferring the issue to clevertap-react-native repo.
