### ISSUE TITLE
[Android] SecurityException - Compiling under/targeting SDK 30 causes crash on startup 

### ISSUE THREAD

**Issue by arunabimanyu7** [CleverTap/clevertap-android-sdk#139]
I've been able to reliably reproduce this startup crash on Android when targeting SDK 30 (targeting 29 shows no such issue).

```
com.rizek.android.users.test E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.rizek.android.users.test, PID: 5582
    java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
        at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.getNetworkType(DeviceInfo.java:618)
        at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.<init>(DeviceInfo.java:546)
        at com.clevertap.android.sdk.DeviceInfo.getDeviceCachedInfo(DeviceInfo.java:81)
        at com.clevertap.android.sdk.DeviceInfo.access$000(DeviceInfo.java:23)
        at com.clevertap.android.sdk.DeviceInfo$1.run(DeviceInfo.java:52)
        at java.lang.Thread.run(Thread.java:923)
```
        
getNetworkType is deprecated in Android 11.

getDataNetworkType should be used instead.

**Comment by kumaratulismu** [comment]
Hi @arunabimanyu7,

Can you please check the SDK version which you are using. We have fixed this in v4.0.0.

Please check and confirm on this.

**Comment by arunabimanyu7** [comment]
@kumaratulismu Looks like documentation is not up to date

**Comment by darshanclevertap** [comment]
@arunabimanyu7 Please find the documentation on [Github here](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md) and the [CleverTap documentation here](https://developer.clevertap.com/docs/android-quickstart-guide)
