### ISSUE TITLE
Issue with video push notifications.

### ISSUE THREAD

**Issue by ramkotirapido** [CleverTap/clevertap-android-sdk#14]
Hi,

I was using the latest clevertap SDK in my android project.
implementation 'com.clevertap.android:clevertap-android-sdk:3.3.1'

My App is getting crashed when I send the video push notifications.
Exception: Error inflating class com.google.android.exoplayer2.ui.PlayerView

Attaching the exception logcat:

> Caused by android.view.InflateException: Binary XML file line #59: Binary XML file line #59: Error inflating class com.google.android.exoplayer2.ui.PlayerView
       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at com.clevertap.android.sdk.CTInAppNativeInterstitialFragment.onCreateView(CTInAppNativeInterstitialFragment.java:4)
       at android.app.Fragment.performCreateView(Fragment.java:2220)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
       at android.app.BackStackRecord.run(BackStackRecord.java:793)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
       at android.app.FragmentController.execPendingActions(FragmentController.java:325)
       at android.app.Activity.performStart(Activity.java:6339)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5451)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by darshanclevertap** [comment]
@ramkotirapido This has been fixed in v3.3.2 and I would recommend you to update to the latest SDK version which is v3.3.3. Thanks!
