### ISSUE TITLE
SecurityException in getDataNetworkTypeForSubscriber

### ISSUE THREAD

**Issue by paragmrsool** [CleverTap/clevertap-android-sdk#148]
**Clevertap SDK version** 'com.clevertap.android:clevertap-android-sdk:**3.5.1**'
compileSdkVersion **30**  targetSdkVersion **30**
```
java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
        at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.getNetworkType(DeviceInfo.java:569)
        at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.<init>(DeviceInfo.java:499)
        at com.clevertap.android.sdk.DeviceInfo.getDeviceCachedInfo(DeviceInfo.java:71)
        at com.clevertap.android.sdk.DeviceInfo.access$000(DeviceInfo.java:24)
        at com.clevertap.android.sdk.DeviceInfo$1.run(DeviceInfo.java:50)
        at java.lang.Thread.run(Thread.java:923)
```
Continuously App Crash after few seconds.

Working fine with compileSdkVersion **29** and targetSdkVersion **29**

**Comment by darshanclevertap** [comment]
@paragmrsool Please update to CleverTap Android SDK v4.0.2 and follow the [breaking changes here](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md) which were made as a part of v4.0.0
