### ISSUE TITLE
Production -> Clever Tap -> Null pointer Exception 

### ISSUE THREAD

**Issue by arunabimanyu7** [CleverTap/clevertap-android-sdk#151]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.clevertap.android.sdk.CTInboxStyleConfig.getNavBarTitle()' on a null object reference
       at com.clevertap.android.sdk.CTInboxActivity.onCreate(CTInboxActivity.java:76)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Device ->  

Nexus 4
6.0.1

SDK version -> 

4.0.2

Audience  -> 

Many marshmallow users are facing this issue

**Comment by darshanclevertap** [comment]
@arunabimanyu7 
Are you using 
`showAppInbox(CTInboxStyleConfig styleConfig)`
or
`showAppInbox()`
in your app?

**Comment by arunabimanyu7** [comment]
@darshanclevertap We are not using the AppInbox in our application

**Comment by darshanclevertap** [comment]
@arunabimanyu7 This crash is not possible if you're not using the AppInbox methods. Are you sure you were not using AppInbox methods in some previous releases of the app?

**Comment by darshanclevertap** [comment]
@arunabimanyu7 Any update here?
