### ISSUE TITLE
[Exoplayer] InAppMessaging with video or audio doesn't work

### ISSUE THREAD

**Issue by ivannarino** [CleverTap/clevertap-android-sdk#155]
I am trying to display an interstitial with video or audio but none of them work.

I get the following error log

```
2021-02-23 18:20:18.883 22149-22331/com.xxx.staging E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

![image](https://user-images.githubusercontent.com/5160934/108921355-33722f00-7604-11eb-8d44-afab6430ba5f.png)

![image](https://user-images.githubusercontent.com/5160934/108921417-4edd3a00-7604-11eb-9321-db875956515d.png)

**Version: 4.0.3**
**ExoPlayer: 2.11.5**

**Comment by piyush-kukadiya** [comment]
@ivannarino Which url are you using?

**Comment by piyush-kukadiya** [comment]
@ivannarino Can you share video that you are trying to upload on CT?

**Comment by darshanclevertap** [comment]
@ivannarino Can you tell us if you're still facing this issue?
