### ISSUE TITLE
StrictMode policy violation; ~duration=455 ms on main thread

### ISSUE THREAD

**Issue by anjalsaneen** [CleverTap/clevertap-android-sdk#156]
Clevertap is doing IO Operation on the main thread on app onCreate through activity lifecycle callbacks

```
13458-13458 D/StrictMode: StrictMode policy violation; ~duration=455 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:261)
        at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:287)
        at com.clevertap.android.sdk.StorageHelper.getString(StorageHelper.java:25)
        at com.clevertap.android.sdk.LocalDataStore.getStringFromPrefs(LocalDataStore.java:776)
        at com.clevertap.android.sdk.LocalDataStore.getEventDetail(LocalDataStore.java:711)
        at com.clevertap.android.sdk.CleverTapAPI.setLastVisitTime(CleverTapAPI.java:4008)
        at com.clevertap.android.sdk.CleverTapAPI.<init>(CleverTapAPI.java:175)
        at com.clevertap.android.sdk.CleverTapAPI.instanceWithConfig(CleverTapAPI.java:564)
        at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:515)
        at com.clevertap.android.sdk.CleverTapAPI.createInstanceIfAvailable(CleverTapAPI.java:784)
        at com.clevertap.android.sdk.CleverTapAPI.onActivityCreated(CleverTapAPI.java:334)
        at com.clevertap.android.sdk.CleverTapAPI.onActivityCreated(CleverTapAPI.java:279)
        at com.clevertap.android.sdk.ActivityLifecycleCallback$1.onActivityCreated(ActivityLifecycleCallback.java:41)
        at android.app.Application.dispatchActivityCreated(Application.java:373)
        at android.app.Activity.dispatchActivityCreated(Activity.java:1202)
        at android.app.Activity.onCreate(Activity.java:1475)
        at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:154)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:312)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
        at tech.okcredit.android.base.activity.OkcActivity.onCreate(OkcActivity.kt:44)
        at in.okcredit.navigation.NavigationActivity.onCreate(NavigationActivity.kt:81)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by darshanclevertap** [comment]
@anjalsaneen Sorry for the delay in getting back here. Can you mention which SDK version are you using?

**Comment by anjalsaneen** [comment]
@darshanclevertap 

Version: 3.9.0

**Comment by darshanclevertap** [comment]
@anjalsaneen Please provide an update here as well after upgrading to CT React Native SDK 0.5.0

**Comment by anjalsaneen** [comment]
Sure

**Comment by darshanclevertap** [comment]
@anjalsaneen Are you still facing this issue?

**Comment by anjalsaneen** [comment]
No @darshanclevertap. We are not having this in the latest version of clevertap. although `com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService` service wakes up when the phone is on killed state or background and that is causing ANR on firebase and other apps due to lack of processing power in the App. May I know how often this service run?
<img width="1482" alt="Screenshot 2021-06-03 at 8 46 26 AM" src="https://user-images.githubusercontent.com/43947967/120581295-31600d80-c448-11eb-873a-2cb6443b0b51.png">

**Comment by darshanclevertap** [comment]
@anjalsaneen Could you help us with a few details? Are you using the native Android SDK or the React Native SDK? Also please share the version of the SDK you're using currently. And the devices on which this ANR occurs.

If you could share the detailed logs of this ANR then it will be helpful for us to figure out if the ANR is being caused by the logic of our SDK or the other reason could be due to the startup of the Service, the app is loading multiple SDKs causing the device to go into ANR mode.

**Comment by anjalsaneen** [comment]
1. Are you using the native Android SDK or the React Native SDK?   React Native SDK 0.5.1
2. The ANR's are not due to clevertap. basically, clever tap wakes up the app occasionally for running the service. whenever the app process wakes up, it has to initialise all content providers. we have firebase crashalytics and performance (it's well known for ANR's). that is causing ANR's. The one way to reduce is not to wakes up the app very often.

**Comment by darshanclevertap** [comment]
@anjalsaneen As I explained the CTBackgroundJobService wakes up to sync with our servers to increase the delivery rate for Push Notifications as a part of Push Amplification. It wakes up every 4 hours to check whether a device is qualified to receive amplified Push Notifications. If there's a concern about the number of wake-ups, you can raise a ticket with our support team via the Dashboard, and the 4 hours time interval can be increased for your account.

**Comment by anjalsaneen** [comment]
No. ANR is still acceptable range. Thanks for update
