### ISSUE TITLE
Null pointer Exception on resuming app from recent app tray in full screen video. v3.3.4

### ISSUE THREAD

**Issue by anubhavpandey-kiwi** [CleverTap/clevertap-android-sdk#16]
java.lang.RuntimeException: Unable to resume activity {com.clevertap.android.sdk.InAppNotificationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setVisibility(int)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3121)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setVisibility(int)' on a null object reference
        at com.clevertap.android.sdk.CTInAppNativeInterstitialFragment.prepareMedia(CTInAppNativeInterstitialFragment.java:208)
        at com.clevertap.android.sdk.CTInAppNativeInterstitialFragment.onResume(CTInAppNativeInterstitialFragment.java:310)
        at android.app.Fragment.performResume(Fragment.java:2263)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
        at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1965)
        at android.app.FragmentController.dispatchResume(FragmentController.java:174)
        at android.app.Activity.performResume(Activity.java:6356)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5443) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by darshanclevertap** [comment]
Fixed with release [v3.4.1](https://github.com/CleverTap/clevertap-android-sdk/releases/tag/3.4.1)
