### ISSUE TITLE
Getting ANR on production app

### ISSUE THREAD

**Issue by athulantonynp** [CleverTap/clevertap-android-sdk#178]
Here is the log
`
  java.lang.RuntimeException: Unable to start activity ComponentInfo{me.entri.entrime/com.clevertap.android.sdk.InAppNotificationActivity}: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.clevertap.android.sdk.L.z.values []
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3574)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3731)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:100)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2167)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7727)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.clevertap.android.sdk.L.z.values []
        at java.lang.Enum.enumValues(Enum.java:270)
        at java.lang.Enum.access$000(Enum.java:61)
        at java.lang.Enum$1.create(Enum.java:277)
        at java.lang.Enum$1.create(Enum.java:275)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Enum.valueOf(Enum.java:243)
        at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1841)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1409)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
        at android.os.Parcel.readSerializable(Parcel.java:3500)
        at android.os.Parcel.readValue(Parcel.java:3270)
        at com.clevertap.android.sdk.L.w.<init>(CTInAppNotification.java:9)
        at com.clevertap.android.sdk.L.w$a.createFromParcel(CTInAppNotification.java:1)
        at android.os.Parcel.readParcelable(Parcel.java:3326)
        at android.os.Parcel.readValue(Parcel.java:3219)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3616)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.containsKey(BaseBundle.java:516)
        at android.content.Intent.hasExtra(Intent.java:8355)
        at android.app.Activity.finish(Activity.java:6450)
        at android.app.Activity.finish(Activity.java:6474)
        at com.clevertap.android.sdk.InAppNotificationActivity.finish(InAppNotificationActivity.java:1)
        at com.clevertap.android.sdk.InAppNotificationActivity.onCreate(InAppNotificationActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:8006)
        at android.app.Activity.performCreate(Activity.java:7986)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3547)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3731) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:100) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2167) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7727) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
     Caused by: java.lang.NoSuchMethodException: com.clevertap.android.sdk.L.z.values []
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getDeclaredMethod(Class.java:2081)
        at java.lang.Enum.enumValues(Enum.java:267)
        at java.lang.Enum.access$000(Enum.java:61) 
        at java.lang.Enum$1.create(Enum.java:277) 
        at java.lang.Enum$1.create(Enum.java:275) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Enum.valueOf(Enum.java:243) 
        at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1841) 
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1409) 
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427) 
        at android.os.Parcel.readSerializable(Parcel.java:3500) 
        at android.os.Parcel.readValue(Parcel.java:3270) 
        at com.clevertap.android.sdk.L.w.<init>(CTInAppNotification.java:9) 
        at com.clevertap.android.sdk.L.w$a.createFromParcel(CTInAppNotification.java:1) 
        at android.os.Parcel.readParcelable(Parcel.java:3326) 
        at android.os.Parcel.readValue(Parcel.java:3219) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3616) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.containsKey(BaseBundle.java:516) 
        at android.content.Intent.hasExtra(Intent.java:8355) 
        at android.app.Activity.finish(Activity.java:6450) 
        at android.app.Activity.finish(Activity.java:6474) 
        at com.clevertap.android.sdk.InAppNotificationActivity.finish(InAppNotificationActivity.java:1) 
        at com.clevertap.android.sdk.InAppNotificationActivity.onCreate(InAppNotificationActivity.java:36) 
        at android.app.Activity.performCreate(Activity.java:8006) 
        at android.app.Activity.performCreate(Activity.java:7986) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3547) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3731) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:100) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2167) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7727) 
`

**Comment by darshanclevertap** [comment]
@athulantonynp Are you sure this is an ANR as these are crash logs? Also, can you give us more details like 

- CleverTap SDK Version
- Android version of the device where this issue is being faced
- Device details
- Steps to reproduce if any

**Comment by athulantonynp** [comment]
These are crash logs. The app throws this crash log just before the ANR dialog. That's why I have mentioned it as an ANR. 
Here are the details

1. 4.1.1
2. Pixel 4a (Android 12 beta) ,Redmi k20 pro Android 10
3. Pixel4a, Redmi k20 pro
4. Happening in a random manner. Whenever we open our app in release build, this crash logs and ANR message is shown

**Comment by athulantonynp** [comment]
Also, it is not happening now.

**Comment by darshanclevertap** [comment]
@athulantonynp Is it possible to reproduce this on a debug variant of your app and share the unobfuscated logs? That would help us tremendously in figuring out what is causing this issue.

**Comment by darshanclevertap** [comment]
@athulantonynp Any update? Were you able to reproduce this on a debug variant of the app?
