### ISSUE TITLE
Crash On Background

### ISSUE THREAD

**Issue by anjalsaneen** [CleverTap/clevertap-android-sdk#18]
Device Info:
Name: ONEPLUS A6000
Brand: OnePlus
Android API: 28

Clevertap Version: 3.1.8

StackTrace:
com.clevertap.android.sdk.InAppFCManager
at com.clevertap.android.sdk.InAppFCManager.destroySession(Unknown Source:0)
at com.clevertap.android.sdk.SessionManager.destroySession(SessionManager.java:84)
at com.clevertap.android.sdk.CleverTapAPI.forceDestroySession(CleverTapAPI.java:862)
at com.clevertap.android.sdk.CleverTapAPI.checkTimeoutSession(CleverTapAPI.java:855)
at com.clevertap.android.sdk.CleverTapAPI.access$700(CleverTapAPI.java:48)
at com.clevertap.android.sdk.CleverTapAPI$5.run(CleverTapAPI.java:673)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6863)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Caused By: at com.clevertap.android.sdk.InAppFCManager.attachToHeader(Unknown Source:0)
at com.clevertap.android.sdk.CommsManager.insertHeader(CommsManager.java:361)
at com.clevertap.android.sdk.CommsManager.sendQueue(CommsManager.java:187)
at com.clevertap.android.sdk.CommsManager.flushDBQueue(CommsManager.java:103)
at com.clevertap.android.sdk.CommsManager.flushQueueSync(CommsManager.java:77)
at com.clevertap.android.sdk.CommsManager$1.run(CommsManager.java:56)
at com.clevertap.android.sdk.CleverTapAPI$1.run(CleverTapAPI.java:244)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

**Comment by anjalsaneen** [comment]
I have updated to the latest version. I can update here about this crash happening again on latest version tomorrow.

**Comment by darshanclevertap** [comment]
Can you please update the CleverTap SDK version to [3.4.2](https://github.com/CleverTap/clevertap-android-sdk/releases/tag/3.4.2) and check if this issue still persists?

**Comment by anjalsaneen** [comment]
@darshanclevertap I couldn't able to update yesterday because of Gradle tool version `3.3.0`. Luckily the new version of Gradle tool released today `3.3.1` and I updated CleverTap version to `3.4.2`. I'll let you know tomorrow about the issue still persists.

**Comment by anjalsaneen** [comment]
@darshanclevertap I can see some deprecated code after updating. I can't find any release notes here. can you just verify this `git diff`
<img width="556" alt="screen shot 2019-02-07 at 5 28 28 pm" src="https://user-images.githubusercontent.com/43947967/52410357-1bebaa80-2afe-11e9-9e9b-be7f9192dd34.png">

**Comment by darshanclevertap** [comment]
@anjalsaneen You can go through our [CHANGELOG](https://github.com/CleverTap/clevertap-android-sdk/blob/master/CHANGELOG.md) and [EXAMPLES](https://github.com/CleverTap/clevertap-android-sdk/blob/master/EXAMPLES.md) for the release notes and example usage. But in short, we have deprecated the old ways of raising events and pushing profile properties as a warning, you can still use the same code as it is backward compatible for now. We will be eventually removing the old methods by end of this year or early next year, so if it is not much of a hassle for you can update these methods.

And as for for the AGP update to `3.3.1`, I will also be testing it on my end for any issues related to our SDK.

Hope this helps :)
