### ISSUE TITLE
Getting this kind of exception? Please help asap

### ISSUE THREAD

**Issue by iampawan** [CleverTap/clevertap-android-sdk#2]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{package name/com.clevertap.android.sdk.InAppNotificationActivity}: android.util.AndroidRuntimeException: java.lang.RuntimeException: Invalid reflection
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3190)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3300)
       at android.app.ActivityThread.access$1000(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6946)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:116)
Caused by android.util.AndroidRuntimeException: java.lang.RuntimeException: Invalid reflection
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:130)
       at android.webkit.WebView.getFactory(WebView.java:2207)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2202)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2261)
       at android.view.View.(View.java)
       at android.view.View.(View.java)
       at android.view.ViewGroup.(ViewGroup.java)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at com.clevertap.android.sdk.InAppNotificationActivity$InAppWebView.(InAppNotificationActivity.java)
       at com.clevertap.android.sdk.InAppNotificationActivity.onCreate(InAppNotificationActivity.java:93)
       at android.app.Activity.performCreate(Activity.java:6575)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3143)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3300)
       at android.app.ActivityThread.access$1000(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6946)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:116)
Caused by java.lang.RuntimeException: Invalid reflection
       at com.android.webview.chromium.WebViewDelegateFactory$Api21CompatibilityDelegate.(WebViewDelegateFactory.java)
       at com.android.webview.chromium.WebViewDelegateFactory.createApi21CompatibilityDelegate(WebViewDelegateFactory.java:97)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.(WebViewChromiumFactoryProvider.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.Class.newInstance(Class.java:1690)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:124)
       at android.webkit.WebView.getFactory(WebView.java:2207)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2202)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2261)
       at android.view.View.(View.java)
       at android.view.View.(View.java)
       at android.view.ViewGroup.(ViewGroup.java)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at com.clevertap.android.sdk.InAppNotificationActivity$InAppWebView.(InAppNotificationActivity.java)
       at com.clevertap.android.sdk.InAppNotificationActivity.onCreate(InAppNotificationActivity.java:93)
       at android.app.Activity.performCreate(Activity.java:6575)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3143)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3300)
       at android.app.ActivityThread.access$1000(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6946)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:116)
Caused by java.lang.NoSuchMethodException: callDrawGLFunction [long]
       at java.lang.Class.getMethod(Class.java:671)
       at com.android.webview.chromium.WebViewDelegateFactory$Api21CompatibilityDelegate.(WebViewDelegateFactory.java)
       at com.android.webview.chromium.WebViewDelegateFactory.createApi21CompatibilityDelegate(WebViewDelegateFactory.java:97)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.(WebViewChromiumFactoryProvider.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.Class.newInstance(Class.java:1690)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:124)
       at android.webkit.WebView.getFactory(WebView.java:2207)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2202)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2261)
       at android.view.View.(View.java)
       at android.view.View.(View.java)
       at android.view.ViewGroup.(ViewGroup.java)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at android.webkit.WebView.(WebView.java)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:687)
       at android.webkit.WebView.(<Xposed>)
       at com.clevertap.android.sdk.InAppNotificationActivity$InAppWebView.(InAppNotificationActivity.java)
       at com.clevertap.android.sdk.InAppNotificationActivity.onCreate(InAppNotificationActivity.java:93)
       at android.app.Activity.performCreate(Activity.java:6575)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3143)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3300)
       at android.app.ActivityThread.access$1000(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6946)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:116)

**Comment by judepereira** [comment]
Hey @iampawan, are you running [this](https://github.com/rovo89/XposedBridge)?
