### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError No direct method <init>(Landroid/content/Context;Lcom/google/android/exoplayer2/trackselection/TrackSelection$Factory;)V in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in base.apk!classes2.dex)

### ISSUE THREAD

**Issue by NG-Gaurav** [CleverTap/clevertap-android-sdk#210]
Fatal Exception: java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Lcom/google/android/exoplayer2/trackselection/TrackSelection$Factory;)V in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in base.apk!classes2.dex)
       at com.clevertap.android.sdk.customviews.MediaPlayerRecyclerView.initialize(MediaPlayerRecyclerView.java:192)
       at com.clevertap.android.sdk.customviews.MediaPlayerRecyclerView.<init>(MediaPlayerRecyclerView.java:51)
       at com.clevertap.android.sdk.inbox.CTInboxListViewFragment.onCreateView(CTInboxListViewFragment.java:112)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1830)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
       at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:246)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
       at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
       at android.view.View.measure(View.java:24730)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:24730)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:24730)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:24730)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:24730)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:749)
       at android.view.View.measure(View.java:24730)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3282)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2052)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2354)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1940)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8041)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
       at android.view.Choreographer.doCallbacks(Choreographer.java:986)
       at android.view.Choreographer.doFrame(Choreographer.java:902)
       at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1091)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by darshanclevertap** [comment]
@NG-Gaurav Can you please give some context on when this crash is occurring? Just copy-pasting the stack trace does not help anyone.

Please also provide which version of the CleverTap Android SDK you are currently using and the version of ExoPlayer.

Thanks 😊

**Comment by NG-Gaurav** [comment]
we do not know when it happen. firebase crashlytics is showing this crash.

**Comment by NG-Gaurav** [comment]
CleverTap Android SDK version : - 4.2.0 
 ExoPlayer Android SDK version : - 2.16.1

**Comment by darshanclevertap** [comment]
@NG-Gaurav  Please downgrade your ExoPlayer version to 2.15.1 and see if the crashes continue to occur

**Comment by darshanclevertap** [comment]
@NG-Gaurav For CleverTap Android SDK v4.2.0, please use ExoPlayer v2.11.0
or
update CleverTap Android SDK to v4.3.1 and use ExoPlayer v2.1.5.1

Let us know if you still face the crash

**Comment by NG-Gaurav** [comment]
we can not downgrade your ExoPlayer version. any other solution?

**Comment by darshanclevertap** [comment]
@NG-Gaurav Try using CleverTap Android SDK v4.3.1 and let us know if you still face the issue

**Comment by darshanclevertap** [comment]
@NG-Gaurav Were you able to fix the issue with the latest CleverTap Android SDK?

**Comment by darshanclevertap** [comment]
Closing this for now. Please re-open if you are still facing this issue.
