### ISSUE TITLE
getting some issue after adding com.clevertap.android:clevertap-xiaomi-sdk:1.2.0

### ISSUE THREAD

**Issue by NG-Gaurav** [CleverTap/clevertap-android-sdk#223]
V/XMPush-7008: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:571)
        at android.os.IMessenger$Stub$Proxy.send(IMessenger.java:125)
        at android.os.Messenger.send(Messenger.java:59)
        at com.xiaomi.mipush.sdk.ak.onServiceConnected(Unknown Source:47)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by root-ansh-ct** [comment]
can you share details on how you have implemented the xiaomi sdk? Also please share the following information :

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Logs**
If applicable, add screenshots to help explain your problem.
In case of crashes, share the entire crash logs as a `.txt` file

**Environment (please complete the following information):**
 - Device: [e.g. OnePlus 9 Pro]
 - OS: [e.g. Android 10]
 - CleverTap SDK Version [e.g. v4.x.x]
 - Android Studio Version [e.g. v4.1.2]

**Additional context**
Add any other context about the problem here.

**Comment by NG-Gaurav** [comment]
FATAL EXCEPTION: Connection Controller Thread
    Process: com.viewlift.hoichoi:pushservice, PID: 16880
    java.lang.IllegalArgumentException: com.viewlift.hoichoi: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.xiaomi.push.bo.a(Unknown Source:13)
        at com.xiaomi.push.bo.a(Unknown Source:81)
        at com.xiaomi.push.bn.a(Unknown Source:44)
        at com.xiaomi.push.service.XMPushService.e(Unknown Source:13)
        at com.xiaomi.push.service.XMPushService.a(Unknown Source:0)
        at com.xiaomi.push.service.cg.a(Unknown Source:2)
        at com.xiaomi.push.service.az.a(Unknown Source:76)
        at com.xiaomi.push.service.ad.a(Unknown Source:53)
        at com.xiaomi.push.service.cj.a(Unknown Source:2)
        at com.xiaomi.push.service.XMPushService$j.run(Unknown Source:20)
        at com.xiaomi.push.service.o$c.run(Unknown Source:156)

**Comment by NG-Gaurav** [comment]
this issue related to android 12.

**Comment by NG-Gaurav** [comment]
Any update on it

**Comment by piyush-kukadiya** [comment]
@NG-Gaurav While releasing `clevertap-xiaomi-sdk:1.2.0` Xiaomi didn't supported Android 12. Xiaomi's support for Android 12 comes on `2022.01.27`. We will release the same in first half of FEB. Will update you here for new release.

**Comment by JustinLim0318** [comment]
Hello any updates on this? Samsung device keep crashing due to this issue.

**Comment by piyush-kukadiya** [comment]
@JustinLim0318 We have released [xps 1.3.0](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTXIAOMIPUSHCHANGELOG.md#version-130-march-2-2022). Please use this latest version. 
If issue still persists please raise issue with Xiaomi developers since crash is happening inside xiaomi dependency.
