### ISSUE TITLE
CTBackgroundJobService ClassNotFoundException issue

### ISSUE THREAD

**Issue by rahulr4** [CleverTap/clevertap-android-sdk#225]
Getting this crash on production release build after updated clevertap to 4.0.0
'com.clevertap.android:clevertap-android-sdk:4.4.0'

Fatal Exception: java.lang.RuntimeException: Unable to create service com.clevertap.android.sdk.CTBackgroundJobService: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.CTBackgroundJobService" on path: DexPathList[[zip file "/data/app/~~n4nuVsnftNIqnRfRl3P5sA==/com.dineout.book-9JM_lR5_Uk9BqxFuenQeGw==/base.apk", zip file "/data/app/~~n4nuVsnftNIqnRfRl3P5sA==/com.dineout.book-9JM_lR5_Uk9BqxFuenQeGw==/split_config.arm64_v8a.apk", zip file "/data/app/~~n4nuVsnftNIqnRfRl3P5sA==/com.dineout.book-9JM_lR5_Uk9BqxFuenQeGw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~n4nuVsnftNIqnRfRl3P5sA==/com.dineout.book-9JM_lR5_Uk9BqxFuenQeGw==/lib/arm64, /data/app/~~n4nuVsnftNIqnRfRl3P5sA==/com.dineout.book-9JM_lR5_Uk9BqxFuenQeGw==/base.apk!/lib/arm64-v8a, /data/app/~~n4nuVsnftNIqnRfRl3P5sA==/com.dineout.book-9JM_lR5_Uk9BqxFuenQeGw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~n4nuVsnftNIqnRfRl3P5sA==/com.dineout.book-9JM_lR5_Uk9BqxFuenQeGw==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4391)
       at android.app.ActivityThread.access$1900(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2112)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by darshanclevertap** [comment]
@rahulr4 If you are migrating from a version below v4.0.0 to a version above v4.0.0. Please read this [migration document](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md) for a smooth transition.

**Comment by rahulr4** [comment]
This issue arise when we are upgrading our app from store.
Current app on play store has 3.9.1 version where CTBackgroundJobService class is in the above mentioned package
and now when we have upgrade it to 4.4.0, the package is changed and this crash is coming now

**Comment by darshanclevertap** [comment]
@rahulr4 Proguard has nothing to do with this. This crash is happening because the Android OS is trying to run the job with the old package name, while the package name for the Job has been changed. Ideally, the OS should not keep an instance of existing jobs when an app upgrade happens.
This is not something we can fix, over time, these crashes will reduce as the majority of your userbase will move to the new version with CT SDK v4.4.0 and launch/re-launch your app on a daily basis.

**Comment by piyush-kukadiya** [comment]
@rahulr4 Closing this due to inactivity. Please reopen again if required.
