### ISSUE TITLE
App inbox crash

### ISSUE THREAD

**Issue by onesand** [CleverTap/clevertap-android-sdk#229]
clevertap-android-sdk:4.4.0
exoplay:2.12.0

My inbox style:
```
CTInboxStyleConfig styleConfig = new CTInboxStyleConfig();
styleConfig.setTabBackgroundColor("#000000");
styleConfig.setSelectedTabIndicatorColor("#FFBF00");
styleConfig.setSelectedTabColor("#FFBF00");
styleConfig.setUnselectedTabColor("#FFFFFF");
styleConfig.setBackButtonColor("#FFFFFF");
styleConfig.setNavBarTitleColor("#FFFFFF");
styleConfig.setNavBarTitle(getString(R.string.inbox_title));
styleConfig.setNavBarColor("#000000");
styleConfig.setInboxBackgroundColor("#000000");
styleConfig.setNoMessageViewText(getString(R.string.inbox_no_message));
styleConfig.setNoMessageViewTextColor("#FFFFFF");

cleverTapDefaultInstance.showAppInbox(styleConfig); 
```
crash:
```
java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Lcom/google/android/exoplayer2/trackselection/ExoTrackSelection$Factory;)V in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in /data/app/com.viu.phone-YknyLEPpPZavlv6D6hXxQQ==/base.apk!classes2.dex)
        at com.clevertap.android.sdk.customviews.MediaPlayerRecyclerView.initialize(MediaPlayerRecyclerView.java:188)
        at com.clevertap.android.sdk.customviews.MediaPlayerRecyclerView.<init>(MediaPlayerRecyclerView.java:47)
        at com.clevertap.android.sdk.inbox.CTInboxListViewFragment.onCreateView(CTInboxListViewFragment.java:112)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
        at android.app.Activity.performStart(Activity.java:7847)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by darshanclevertap** [comment]
@onesand As mentioned in the CleverTap's [Usage documentation](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/EXAMPLES.md#using-app-inbox), for the App Inbox, you will have to update your Exoplayer dependency from 2.12.0 to 2.15.1 for smooth functioning of the App Inbox feature.

**Comment by onesand** [comment]
@darshanclevertap Thanks for help. Is exoplayer must 2.15.1? ex:2.14.2、2.14.0

**Comment by darshanclevertap** [comment]
@onesand Yes, v2.1.5.1 of Exoplayer is a must for CleverTap Android SDK v4.4.0 😇

**Comment by onesand** [comment]
Thanks a lot! I can't upgrade the exoplayer version now, because it exists in another sdk, can you provide the exoplayer version used by different clevetap?

**Comment by darshanclevertap** [comment]
@onesand For CleverTap SDK v4.0.0 to v4.2.0, you can use ExoPlayer v2.11.5

**Comment by onesand** [comment]
@darshanclevertap Thanks a lot, solved my problem.
