### ISSUE TITLE
NoSuchMethodError in CTSimpleMessageViewHolder.configureWithMessage()

### ISSUE THREAD

**Issue by ghataa** [CleverTap/clevertap-android-sdk#25]
Hey guys,

I get the following error when I try to open appInbox:

```
java.lang.NoSuchMethodError: No virtual method placeholder(I)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions'
        at com.clevertap.android.sdk.CTSimpleMessageViewHolder.configureWithMessage(CTSimpleMessageViewHolder.java:218)
        at com.clevertap.android.sdk.CTInboxMessageAdapter.onBindViewHolder(CTInboxMessageAdapter.java:49)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6890)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6932)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5852)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6119)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5958)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5954)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2226)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3990)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3402)
        at android.view.View.measure(View.java:18794)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
        at android.view.View.measure(View.java:18794)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
        at android.view.View.measure(View.java:18794)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:18794)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
        at android.view.View.measure(View.java:18794)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
        at android.view.View.measure(View.java:18794)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:18794)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
        at android.view.View.measure(View.java:18794)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
    	at android.view
```

It happens when I try to send a message with a photo.

Currently, I just try to implement app-inbox, so I use a simple configuration like this:

```
        ArrayList<String> tabs = new ArrayList<>();
        tabs.add("Promotions");
        tabs.add("Offers");

        CTInboxStyleConfig styleConfig = new CTInboxStyleConfig();
        styleConfig.setTabs(tabs);
        styleConfig.setTabBackgroundColor("#ffffff");
        styleConfig.setSelectedTabIndicatorColor("#0000FF");
        styleConfig.setSelectedTabColor("#10ddba");
        styleConfig.setUnselectedTabColor("#ffffff");
        styleConfig.setBackButtonColor("#1a1a1a");
        styleConfig.setNavBarTitleColor("#1a1a1a");
        styleConfig.setNavBarTitle("MY INBOX");
        styleConfig.setNavBarColor("#ffffff");
        styleConfig.setInboxBackgroundColor("#ffffff");

        cleverTapDefaultInstance.showAppInbox(styleConfig);
```

Also here are my gradle dependencies:

```
implementation 'androidx.appcompat:appcompat:1.1.0-alpha01'
implementation 'com.google.android.material:material:1.1.0-alpha02'
implementation 'com.github.bumptech.glide:glide:4.9.0'
```

Do you have any idea what's wrong?

**Comment by darshanclevertap** [comment]
Hi @ghataa 

This error is occurring because you have updated the Glide dependency to v4.9.0 and CleverTap Android SDK below v3.4.3 and below need a Glide dependency of v4.8.0. There has been a breaking change when Glide updated to v4.9.0 from v4.8.0 in the `RequestOptions` class. We have handled this error in the CleverTap Android SDK v3.5.1 so I would suggest you to update to our latest version.

Thanks!

**Comment by ghataa** [comment]
@darshanclevertap thank you, updating CleverTap sdk to v3.5.1 solved my problem!
