### ISSUE TITLE
java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by ghataa** [CleverTap/clevertap-android-sdk#26]
Hi,

I try to use videos (mp4) in In-app messages and App inbox but when I try to send a test In-app message or open the built-in App inbox screen with `cleverTapDefaultInstance.showAppInbox(styleConfig)` I get the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
    java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.source.BaseMediaSource.prepareSourceInternal(com.google.android.exoplayer2.upstream.TransferListener)"
        at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:140)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:444)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:311)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

I use the following versions:

```
implementation 'com.clevertap.android:clevertap-android-sdk:3.5.1'
implementation 'com.google.android.exoplayer:exoplayer-core:2.10.1'
implementation 'com.google.android.exoplayer:exoplayer-ui:2.10.1'
```

Have you ever faced this issue?

**Comment by darshanclevertap** [comment]
@ghataa Can you help me with a couple of things?
1. Does this crash still happen if you add 
`implementation 'com.google.android.exoplayer:exoplayer-hls:2.10.1'` ?
2. Do you have any special requirement to move to Exoplayer v2.10.1 which can't work with v2.8.4?

**Comment by ghataa** [comment]
`com.google.android.exoplayer:exoplayer-hls` solved it, thank you!

But now what I can see is only a thumbnail with a circular progress bar. The video doesn't load and I get the following:

```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:306)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:251)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

Is it a permission issue?

**Comment by darshanclevertap** [comment]
@ghataa Could be a network issue? Videos are stored in the CleverTap CDN when it comes to In-Apps and Inbox notifications. Can you try on a different network and let me know? If the issue persists I will redirect it to the concerned team.

**Comment by ghataa** [comment]
I tried on two different networks but didn't solve the problem. Do you need any other information?

**Comment by darshanclevertap** [comment]
@ghataa Give me some time to see the various reasons why this could be happening. I will get back to you by tomorrow on this with the next steps. Thank you for your patience 🙂

**Comment by ghataa** [comment]
Ok, thank you!

**Comment by ghataa** [comment]
@darshanclevertap is there any further progress?

**Comment by darshanclevertap** [comment]
@ghataa Sorry for the delay, are you still facing this issue?

**Comment by ghataa** [comment]
@darshanclevertap no worries! Unfortunately, yes.

**Comment by darshanclevertap** [comment]
Hi @ghataa Sorry for the delay. Are you still facing this issue and if yes, can you share with the latest logs?

**Comment by ghataa** [comment]
Hi @darshanclevertap! It seems that something was wrong with the used mp4, because everything works fine if I try with another one. But I'll let you know if I also face this issue in the future.
