### ISSUE TITLE
[Crash] ExceptionInInitializerError at jacocoInit in CleverTapInstanceConfig

### ISSUE THREAD

**Issue by joel-meesho** [CleverTap/clevertap-android-sdk#294]
**Describe the bug**
We recently updated to Clevertap SDK version 4.5.0 and we're seeing the following crash in production

Stack trace

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.clevertap.android.sdk.CleverTapInstanceConfig.$jacocoInit(CleverTapInstanceConfig.java)
       at com.clevertap.android.sdk.CleverTapInstanceConfig.<clinit>(CleverTapInstanceConfig.java:24)

-- 

Caused by java.util.ConcurrentModificationException
       at java.util.Hashtable$Enumerator.next(Hashtable.java:1187)
       at org.jacoco.agent.rt.internal_28bab1d.ConfigLoader.loadSystemProperties(ConfigLoader.java:56)
       at org.jacoco.agent.rt.internal_28bab1d.ConfigLoader.load(ConfigLoader.java:37)
       at org.jacoco.agent.rt.internal_28bab1d.Offline.<clinit>(Offline.java:29)
       at com.clevertap.android.sdk.CleverTapInstanceConfig.$jacocoInit(CleverTapInstanceConfig.java)
       at com.clevertap.android.sdk.CleverTapInstanceConfig.<clinit>(CleverTapInstanceConfig.java:24)
```

**To Reproduce**
Unable to reproduce

**Environment (please complete the following information):**
- Majority of the issues are seen on Android OS 7
- We are creating 2 instances of the SDK on the app start

<img width="334" src="https://user-images.githubusercontent.com/53558675/178651041-690f1713-cbac-43f5-b0be-880f084c6dad.png">

**Comment by root-ansh-ct** [comment]
Hello @joel-meesho , Thank you for reporting this. Can you try updating the SDK to 4.5.1 and let  us know if it resolves the issue?
