### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.clevertap.android.sdk.InAppNotificationActivity}

### ISSUE THREAD

**Issue by kaviskhandelwal** [CleverTap/clevertap-android-sdk#320]
**Describe the bug**
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.clevertap.android.sdk.InAppNotificationActivity}: java.lang.RuntimeException: Window couldn't find content container view

**To Reproduce**
1 On Android 6
2 Sending an InAppNotification is causing this exception.

**Expected behavior**
Should not cause any exception or error while sending push notification.

**Screenshots/Logs**
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.clevertap.android.sdk.InAppNotificationActivity}: java.lang.RuntimeException: Window couldn't find content container view
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Environment (please complete the following information):**
 - Device: Multiple
 - OS: Android 6
 - CleverTap SDK Version 4.5.1

**Additional context**
This crash spike every time in-app notifications are sent

**Comment by shivamsharma2710** [comment]
Hi @kaviskhandelwal 

Thanks for reporting the issue. To start the investigation, please provide the following details: 

1. On which build variant(debug/release) the issue reproduces? 

2. A list of other devices with their API Level on which the same issue reproduces? 

3. What are the versions of `androidx.fragment:fragment`
and `androidx.fragment:fragment-ktx` dependencies, if you’re consuming via Gradle?

**Comment by darshanclevertap** [comment]
@kaviskhandelwal Closing this due to no response from your end. Please feel free to reopen this if you are still facing this issue
