### ISSUE TITLE
java.lang.RuntimeException: Unable to instantiate receiver com.clevertap.android.xps.XiaomiMessageReceiver

### ISSUE THREAD

**Issue by NG-Gaurav** [CleverTap/clevertap-android-sdk#323]
Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver com.clevertap.android.xps.XiaomiMessageReceiver: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.xps.XiaomiMessageReceiver" on path: DexPathList[[zip file "/data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/base.apk", zip file "/data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.arm64_v8a.apk", zip file "/data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.en.apk", zip file "/data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/lib/arm64, /data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/base.apk!/lib/arm64-v8a, /data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.en.apk!/lib/arm64-v8a, /data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4165)
       at android.app.ActivityThread.access$1700(ActivityThread.java:263)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

Caused by java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.xps.XiaomiMessageReceiver" on path: DexPathList[[zip file "/data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/base.apk", zip file "/data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.arm64_v8a.apk", zip file "/data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.en.apk", zip file "/data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/lib/arm64, /data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/base.apk!/lib/arm64-v8a, /data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.en.apk!/lib/arm64-v8a, /data/app/~~5j7jNPGhM9LPRLIEWJCoeA==/com.viewlift.hoichoi-emy3N4d_MeOnTpGU7vxNIw==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
       at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4158)
       at android.app.ActivityThread.access$1700(ActivityThread.java:263)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by NG-Gaurav** [comment]
we are using below dependency 
implementation "com.clevertap.android:clevertap-android-sdk:4.6.1"
implementation "com.clevertap.android:clevertap-xiaomi-sdk:1.5.0"

**Comment by NG-Gaurav** [comment]
Code implementation 

private fun initializeCleverTap(context: Context) {
        ActivityLifecycleCallback.register(application)
        CleverTapAPI.enableXiaomiPushOn(PushConstants.XIAOMI_MIUI_DEVICES)
        CleverTapAPI.changeCredentials(ID, TOKEN)
        CleverTapAPI.getDefaultInstance(context)?.let {
            it.initializeInbox()
            it.ctPushAmpListener = application
            it.enableDeviceNetworkInfoReporting(true)
        }
        CleverTapAPI.createNotificationChannel(context.applicationContext, appName, appName, appName, NotificationManager.IMPORTANCE_MAX, true)
    }

**Comment by NG-Gaurav** [comment]
Any update on it

**Comment by piyush-kukadiya** [comment]
@NG-Gaurav Please check release notes to avoid error. https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTXIAOMIPUSHCHANGELOG.md#version-150-september-6-2022
