### ISSUE TITLE
Getting this error after integrating Mipush library for Xiaomi integration  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/xiaomi/push/r;

### ISSUE THREAD

**Issue by prateekvijay** [CleverTap/clevertap-android-sdk#345]
**Describe the bug**

**To Reproduce**
1. Integrate Mipush library and build and launch the app. The app crashes .

**Expected behavior**
App should not crash

**Screenshots/Logs**
In case of crashes, share the entire crash logs as a `.txt` file

**Environment (please complete the following information):**
 - Device: One plus 6
 - OS: Android 11
 - CleverTap SDK Version : 4.6.1
 - Android Studio Version Android Studio Dolphin

**Additional context**

**Comment by prateekvijay** [comment]
Hi,yes we are using proguard but that is in release build not in debug build and this crash is coming in debug build. Yes we are using multidex with dynamic features.

**Comment by piyush-kukadiya** [comment]
@prateekvijay What about https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTXIAOMIPUSHCHANGELOG.md#version-150-september-6-2022 ?

**Comment by prateekvijay** [comment]
Yes i have followed these steps, But still the crash comes.
            java.lang.NoClassDefFoundError: Failed resolution of: Lcom/xiaomi/push/r;
                                                                                                    	at com.xiaomi.push.cx.<clinit>(Unknown Source:0)
                                                                                                    	at com.xiaomi.push.cx.a(Unknown Source:0)
                                                                                                    	at com.xiaomi.push.service.XMPushService.d(Unknown Source:136)
                                                                                                    	at com.xiaomi.push.service.XMPushService.d(Unknown Source:1580)
                                                                                                    	at com.xiaomi.push.service.XMPushService.a(Unknown Source:0)
                                                                                                    	at com.xiaomi.push.service.XMPushService$i.a(Unknown Source:4)
                                                                                                    	at com.xiaomi.push.service.XMPushService$j.run(Unknown Source:20)
                                                                                                    	at com.xiaomi.push.service.o$c.run(Unknown Source:156)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xiaomi.push.r" on path: DexPathList[[zip file "/data/app/~~wMl4Z-_6j6SqBDZ2F9foqw==/com.ril.ajio-OePj5F9fDBtGw6fLCKo5Mg==/base.apk"],nativeLibraryDirectories=[/data/app/~~wMl4Z-_6j6SqBDZ2F9foqw==/com.ril.ajio-OePj5F9fDBtGw6fLCKo5Mg==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.xiaomi.push.cx.<clinit>(Unknown Source:0) 
                                                                                                    	at com.xiaomi.push.cx.a(Unknown Source:0) 
                                                                                                    	at com.xiaomi.push.service.XMPushService.d(Unknown Source:136) 
                                                                                                    	at com.xiaomi.push.service.XMPushService.d(Unknown Source:1580) 
                                                                                                    	at com.xiaomi.push.service.XMPushService.a(Unknown Source:0) 
                                                                                                    	at com.xiaomi.push.service.XMPushService$i.a(Unknown Source:4) 
                                                                                                    	at com.xiaomi.push.service.XMPushService$j.run(Unknown Source:20) 
                                                                                                    	at com.xiaomi.push.service.o$c.run(Unknown Source:156)

**Comment by piyush-kukadiya** [comment]
@prateekvijay I still feel it might be integration issue because [Sample app](https://github.com/CleverTap/clevertap-android-sdk/tree/master/sample) is working and tested internally. Please check if dependencies for clevertap-core and XPS are compatible with each other. Got to external libraries in android studio and check dependencies versions are resolved/downloaded correctly in your project.

**Comment by prateekvijay** [comment]
It crashes 3 out of 10 times .And also the crash points to Mipush library

**Comment by root-ansh-ct** [comment]
@prateekvijay  Hi can you confirm the following details: 
1. if you have the Xiaomi SDK AAR inside the  `libs` folder?
2. if you are using a custom Xiaomi implementation or Clevertap XPS SDK  for sending notifications?

**Comment by darshanclevertap** [comment]
@prateekvijay Closing this due to inactivity. Please feel free to reopen if you have the responses to our questions. Thanks!

**Comment by prateekvijay** [comment]
@root-ansh-ct , we have placed xiaomi push sdk library in libs folder
