### ISSUE TITLE
StrictMode - Disk Read Violation

### ISSUE THREAD

**Issue by prempalsingh** [CleverTap/clevertap-android-sdk#35]
There are a lot of StrictMode violations (mainly DB read/write on main thread) in the Clevertap SDK. Here's one example from the init call itself.

StrictMode policy violation; ~duration=879 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1438)
        at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:233)
        at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:254)
        at com.clevertap.android.sdk.StorageHelper.getString(StorageHelper.java:31)
        at com.clevertap.android.sdk.LocalDataStore.getStringFromPrefs(LocalDataStore.java:776)
        at com.clevertap.android.sdk.LocalDataStore.getEventDetail(LocalDataStore.java:711)
        at com.clevertap.android.sdk.CleverTapAPI.setLastVisitTime(CleverTapAPI.java:3598)
        at com.clevertap.android.sdk.CleverTapAPI.<init>(CleverTapAPI.java:147)
        at com.clevertap.android.sdk.CleverTapAPI.instanceWithConfig(CleverTapAPI.java:509)
        at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:460)
        at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:475)

**Comment by darshanclevertap** [comment]
@prempalsingh Thank you for getting this to our attention, can you please provide a few details to us so that we can help you resolve this issue?
1. Which version of the CleverTap SDK are you using?
2. Detailed logs of the Strict Mode policy violations
We will look into this and get back to you.
Thanks!

**Comment by prempalsingh** [comment]
1. 3.6.1
2. Those are the full logs. The stacktrace I mentioned above originates when I call `CleverTapAPI.getDefaultInstance(context)` from my code. I have removed the part of the stacktrace where I call the method for brevity.

You'd be able to reproduce this by adding the following code to your app before initializing Clevertap.

```
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
    .detectAll()
    .penaltyLog()
    .build());
StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
    .detectAll()
    .penaltyLog()
    .build());
```

**Comment by darshanclevertap** [comment]
@kumaratulismu Can we check this out before the next version release?

**Comment by kumaratulismu** [comment]
@prempalsingh Have checked it from our end. We are storing some configurations in the sharedprefences which could be used next time onwards during the initialisation.

We will maintain it as of now, as this should not impact the performance of the app as we are doing it only once & storing only a few strings.

If you are able to capture performance impact findings, feel free to share with us.

**Comment by prempalsingh** [comment]
@kumaratulismu Any disk read/write including those on SharedPreferences on main thread is a performance issue. Can you not move it to a background thread?

We have a lot of ANRs on low end phones caused by SharedPreferences read/write by Clevertap.

**Comment by kumaratulismu** [comment]
@prempalsingh Correct! Are you using Push Amplification in your application?

**Comment by darshanclevertap** [comment]
@prempalsingh For a better resolution of this issue, I'd suggest you send us the ANR logs to support@clevertap.com
Just mention this Github issue and it will be fast-tracked directly to us for a quick resolution.
I'll close this issue here.
