### ISSUE TITLE
[CTInApp][Crash] Crash on CTInAppNotifications in Obfuscated Release Builds

### ISSUE THREAD

**Issue by karthick-rapido** [CleverTap/clevertap-android-sdk#385]
**Describe the bug**
Firebase Crash Reported inside CTInAppBaseFragment 

**To Reproduce**
1. Configure Clevertap InApp Event
2. Generate a minified Release Build
3. Wait for InAppEvent to show
4. Observe Crash

**Expected behavior**

**Screenshots/Logs**
```
Fatal Exception: java.lang.ClassCastException: com.rapido.rider.v2.ui.earnings_detail.EarningsDetailActivity cannot be cast to fa.o
       at com.clevertap.android.sdk.inapp.CTInAppBaseFragment.onAttach(CTInAppBaseFragment.java:57)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2954)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:463)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:349)
       at android.app.ActivityThread.main(ActivityThread.java:8241)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Environment (please complete the following information):**
 - Device: Any (Xiaomi , Vivo, OnePlus, Infinity as per Firebase)
 - OS: Any
 - CleverTap SDK Version [e.g. v4.x.x]
 - Android Studio Version [e.g. v4.1.2]

**Additional context**
> Looks like current Activity is attempted to be cast to. `DidClickForHardPermissionListener` which resulted in the crash

**Comment by piyush-kukadiya** [comment]
@karthick-rapido Which version are you using?

**Comment by piyush-kukadiya** [comment]
@karthick-rapido If you are using `4.7.0`, it is a known bug not related to proguard and fixed in `4.7.2` Please use latest version.

**Comment by karthick-rapido** [comment]
@piyush-kukadiya  Alright thanks for the clarifications. 
We are using 4.7.0 . Will upgrade to 4.7.2

**Comment by karthick-rapido** [comment]
Hey By Upgrading do you  recommend to upgrade to 4.7.2 or 4.7.4 ?

**Comment by piyush-kukadiya** [comment]
@karthick-rapido If you have plans releasing before Monday then I would recommend 4.7.3 or else we are going to release v4.7.4 by Monday with internal fixes and performance improvements

**Comment by piyush-kukadiya** [comment]
@karthick-rapido v4.7.4 is live, would recommend to use it.
