### ISSUE TITLE
Caused by java.lang.ClassNotFoundException: com.clevertap.android.sdk.Logger

### ISSUE THREAD

**Issue by animeshPE91** [CleverTap/clevertap-android-sdk#389]
Caused by java.lang.ClassNotFoundException: com.clevertap.android.sdk.Logger

Fatal Exception: java.lang.RuntimeException: Unable to start receiver e.c.b.b.openContextMenu: java.lang.ClassNotFoundException: com.clevertap.android.sdk.Logger
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4471)
       at android.app.ActivityThread.access$1800(ActivityThread.java:277)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2172)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8299)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

 - Device: Multiple devices
 - OS: [e.g. Android 10, Android 12, Android 13]
 - CleverTap SDK Version 4.6.6
 - CleverTap push template 1.0.2
 - CleverTap Rendermax sdk 1.0.1
 - Android Studio Version Android Studio Dolphin

Can someone look into this issue

**Comment by piyush-kukadiya** [comment]
@animeshPE91 This is fixed in RenderMax 1.0.2 https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTRENDERMAXCHANGELOG.md#version-102-january-25-2023
