### ISSUE TITLE
Crash in CTInAppBaseFragment - CleverTap SDK 3.5.1

### ISSUE THREAD

**Issue by maulikhirani** [CleverTap/clevertap-android-sdk#39]
Got one crash in one of the latest production version of the [WAY app in Android](https://play.google.com/store/apps/details?id=way.com).
**SDK Version: 3.5.1**

**Crash Details:**
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getBaseContext()' on a null object reference
       at com.clevertap.android.sdk.CTInAppBaseFragment.b(CTInAppBaseFragment.java:13)
       at com.clevertap.android.sdk.CTInAppBasePartialNativeFragment$GestureListener$1.onAnimationEnd(CTInAppBasePartialNativeFragment.java:5)
       at android.view.animation.Animation$3.run(Animation.java:387)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)`

Though crash seems very rare,
by looking at the code in CTInAppBaseFragment, I would suggest adding a null check on getActivity() wherever used.

**Comment by darshanclevertap** [comment]
@maulikhirani Thank you for getting this to our notice. We will take a look at this and keep you updated.

**Comment by kumaratulismu** [comment]
@maulikhirani Thanks for reporting this. We have done the required changes. Our next SDK version should fix this.
