### ISSUE TITLE
Crash: RuntimeException - Parcel Unmarshalling unknown type code XX at offset YY.

### ISSUE THREAD

**Issue by a-blekot** [CleverTap/clevertap-android-sdk#421]
Hello) I've created an issue here because, in the last release of our app, we added CleverTap analytics to our code
```
"com.clevertap.android:clevertap-android-sdk:4.7.5"
"com.clevertap.android:clevertap-segment-android:1.5.0"
```
And new crash appeared in Crashlytics at the same time, so I suppose it could be related to CleverTap lib)

> **Fatal Exception: java.lang.RuntimeException**
> Unable to start activity ComponentInfo{SingleFragmentActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@952ddad: Unmarshalling unknown type code 57 at offset 2204
```
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3751)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3919)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loopOnce(Looper.java:238)
at android.os.Looper.loop(Looper.java:357)
at android.app.ActivityThread.main(ActivityThread.java:8098)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

> **Caused by java.lang.RuntimeException**
> Parcel android.os.Parcel@952ddad: Unmarshalling unknown type code 57 at offset 2204
```
at android.os.Parcel.readValue(Parcel.java:3306)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:3707)
at android.os.Parcel.readSparseArray(Parcel.java:2845)
at android.os.Parcel.readValue(Parcel.java:3284)
at android.os.Parcel.readArrayMapInternal(Parcel.java:3624)
at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
at android.os.BaseBundle.unparcel(BaseBundle.java:236)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1080)
at androidx.fragment.app.FragmentStateManager.restoreState(FragmentStateManager.java:408)
at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2512)
at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1989)
at androidx.fragment.app.Fragment.onCreate(Fragment.java:1965)
at com.myapp.presentation.base.MviCoreFragment.onCreate(MviCoreFragment.kt:149)
at com.myapp.presentation.main.MainFragment.onCreate(MainFragment.kt:55)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2884)
at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:220)
at com.myapp.presentation.base.MviCoreActivity.onCreate(MviCoreActivity.kt:81)
at com.myapp.presentation.singlefragment.SingleFragmentActivity.onCreate(SingleFragmentActivity.kt:46)
at android.app.Activity.performCreate(Activity.java:8244)
at android.app.Activity.performCreate(Activity.java:8224)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1331)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3724)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3919)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loopOnce(Looper.java:238)
at android.os.Looper.loop(Looper.java:357)
at android.app.ActivityThread.main(ActivityThread.java:8098)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

As I can see crash occurs when the app comes back from the background and Activity is recreated together with Fragments.
I tried to reproduce it with **"Don't keep Activities"** flag turned ON, but I couldn't...

 - Devices: Xiaomi (36%), Samsung (36%), Motorola (9%), Oppo (6%), ...
 - OS: Android 12, 11, 10, 9, ...

Also in this release, we set the target SDK to 33....

That's how we set it up

```
class App : Application() {

    override fun onCreate() {
        ActivityLifecycleCallback.register(this)
        super.onCreate()
        
        initCleverTap()
    }
    
    private fun initCleverTap() {
        CleverTapAPI.setDebugLevel(
            if (BuildConfig.DEBUG) CleverTapAPI.LogLevel.DEBUG else CleverTapAPI.LogLevel.OFF
        )

        val analytics = Analytics.Builder(applicationContext, conf.segmentSourceWriteKey)
            .logLevel(if (BuildConfig.DEBUG) Analytics.LogLevel.VERBOSE else Analytics.LogLevel.NONE)
            .use(CleverTapIntegration.FACTORY)
            .trackApplicationLifecycleEvents() // Enable this to record certain application events automatically!
            .recordScreenViews() // Enable this to record screen views automatically!
            .build()

        Analytics.setSingletonInstance(analytics)
    }
```

Any suggestions would be appreciated! 🙏🙏🙏

**Comment by darshanclevertap** [comment]
@a-blekot 
The crash stack traces do not have CleverTap mentioned anywhere, so I think the crash occurred when you updated to v4.7.5 looks like a coincidence.

I see that you are using both the CleverTap Android SDK and CleverTap Segment Android SDK.

We are yet to release the CleverTap Segment Android SDK with support for Android 13. 

v1.5.0 of CleverTap Segment SDK internally supports v4.5.2.

v4.7.5 supports Android 13 but we have not released an updated version of Segment

We are currently working on this. I'll let you know once we have an ETA for this.

**Comment by a-blekot** [comment]
@darshanclevertap
thank you! ok, I will continue the investigation.

**Comment by a-blekot** [comment]
@darshanclevertap 
I also created another [issue](https://github.com/CleverTap/clevertap-segment-android/issues/25) on Segment. It happens during `Analytics.Builder().build()`

**Comment by darshanclevertap** [comment]
I see the Segment [issue](https://github.com/CleverTap/clevertap-segment-android/issues/25) has been closed. 
Can I close this now?

**Comment by a-blekot** [comment]
Yes! Thank you!

Actually this issue was caused by another lib - https://github.com/Ferfalk/SimpleSearchView/issues/37
