### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toUpperCase()' on a null object reference

### ISSUE THREAD

**Issue by HGaurav328** [CleverTap/clevertap-android-sdk#435]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toUpperCase()' on a null object reference
       at com.xiaomi.channel.commonutils.android.f.b(f.java:2)
       at com.xiaomi.channel.commonutils.android.f.a(f.java:3)
       at com.xiaomi.push.service.XMPushService.a(XMPushService.java:35)
       at com.xiaomi.push.service.XMPushService.c(XMPushService.java:1)
       at com.xiaomi.push.service.XMPushService.b(XMPushService.java:7)
       at com.xiaomi.push.service.XMPushService$h.a(XMPushService.java:2)
       at com.xiaomi.push.service.XMPushService$j.run(:18)
       at com.xiaomi.push.service.o$c.run(o.java:152)

**Comment by piyush-kukadiya** [comment]
@HGaurav328 Crash is from Xiaomi SDK. They have a new release which says,

```
Version 5.1.5 (updated on 2023.05.23)
Fix some bugs and improve stability
```
Not sure if this crash is fixed in above version but we will release new XPS SDK soon aligning with xiaomi `5.1.5`

**Comment by piyush-kukadiya** [comment]
@HGaurav328 [CleverTap XPS v1.5.3](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTXIAOMIPUSHCHANGELOG.md#version-153-august-10-2023) points to the latest Xiaomi SDK.
