### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by mkansara** [CleverTap/clevertap-android-sdk#57]
After updating SDK to version 3.6.4 i get this error while run time @
**cleverTapAPI = CleverTapAPI.getDefaultInstance(getApplicationContext());**

2020-03-02 12:02:44.942 28921-28921/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.mchannel.peachmode.alpha, PID: 28921
    java.lang.VerifyError: Verifier rejected class com.clevertap.android.sdk.InAppFCManager: int[] com.clevertap.android.sdk.InAppFCManager.getInAppCountsFromPersistentStore(java.lang.String) failed to verify: int[] com.clevertap.android.sdk.InAppFCManager.getInAppCountsFromPersistentStore(java.lang.String): [0x3B] register v2 has type Conflict but expected Integer (declaration of 'com.clevertap.android.sdk.InAppFCManager' appears in /data/app/co.mchannel.peachmode.alpha-1/base.apk:classes4.dex)
        at com.clevertap.android.sdk.CleverTapAPI.<init>(CleverTapAPI.java:141)
        at com.clevertap.android.sdk.CleverTapAPI.instanceWithConfig(CleverTapAPI.java:528)
        at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:479)
        at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:494)
        at co.mchannel.peachmode.PeachmodeApplication.onCreate(PeachmodeApplication.java:146)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by darshanclevertap** [comment]
Same as https://github.com/CleverTap/clevertap-android-sdk/issues/15
Please check the solution provided and let me know if the problem persists
