### ISSUE TITLE
Can't create handler inside thread that has not called  Error after updating to 3.7.0

### ISSUE THREAD

**Issue by nabil6391** [CleverTap/clevertap-android-sdk#61]
Hi Guys, after update to the latest version, Our app is crashing due to the below crash... Can you please have a look

`Fatal Exception: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
       at android.os.Handler.<init>(Handler.java:209)
       at android.os.Handler.<init>(Handler.java:123)
       at com.clevertap.android.sdk.CleverTapAPI.instanceWithConfig(CleverTapAPI.java:538)
       at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:486)
       at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:501)
       at com.clevertap.android.sdk.CleverTapAPI.runJobWork(CleverTapAPI.java:1450)
       at com.clevertap.android.sdk.CTBackgroundJobService$1.run(CTBackgroundJobService.java:19)
       at java.lang.Thread.run(Thread.java:818)
`

**Comment by darshanclevertap** [comment]
@nabil6391 Could you please share some more details like what kind of device and OS version you found this crash on?

**Comment by nabil6391** [comment]
HI thanks for the reply, This is gotten from our crashlytics report... It happens in almost all devices and OS version. I am suspecting its because we are initialisiing the clevertap in a background thread using coroutines in the application class.


![image](https://user-images.githubusercontent.com/21167899/77024950-cb19d700-69ca-11ea-8314-f359b40e0b9b.png)

**Comment by nabil6391** [comment]
Actually Upon further research the crash is actually happening because the CleverTap.getInstance() is being run from the background thread by the library inside the CTBackgroundJobService

Please fix this issue

**Comment by darshanclevertap** [comment]
@nabil6391 Yes, I was able to reproduce this on my end as well. I am working on a release and will give you an update by EOD.

**Comment by nabil6391** [comment]
Awesome thanks a lot

**Comment by darshanclevertap** [comment]
@nabil6391 Fixed this with the latest CleverTap Android SDK v3.7.1
