### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by gauravtyagi328** [CleverTap/clevertap-android-sdk#64]
Crashlytics show below error on deshboard. Please check it
clevertapVersion = "3.7.0"

CleverTapAPI.java line 3951
com.clevertap.android.sdk.CleverTapAPI.displayNotification

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.clevertap.android.sdk.InAppFCManager.a(com.clevertap.android.sdk.CTInAppNotification)' on a null object reference
       at com.clevertap.android.sdk.CleverTapAPI.displayNotification(CleverTapAPI.java:3951)
       at com.clevertap.android.sdk.CleverTapAPI.notificationReady(CleverTapAPI.java:3935)
       at com.clevertap.android.sdk.CleverTapAPI$29.run(CleverTapAPI.java:3924)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by darshanclevertap** [comment]
@gauravtyagi328 This has been fixed in v3.7.2. Please update the CleverTap SDK on your end. Thanks!
