### ISSUE TITLE
StrictMode policy violation; ~duration=102 ms: android.os.strictmode.DiskReadViolation

### ISSUE THREAD

**Issue by HGaurav328** [CleverTap/clevertap-android-sdk#669]
StrictMode policy violation; ~duration=102 ms: android.os.strictmode.DiskReadViolation (Ask Gemini)
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1666)
                                                                                                    	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                                                                                                    	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                                                                                                    	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8054)
                                                                                                    	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:332)
                                                                                                    	at java.io.File.exists(File.java:829)
                                                                                                    	at android.app.ContextImpl.getDataDir(ContextImpl.java:3196)
                                                                                                    	at android.app.ContextImpl.getDir(ContextImpl.java:3215)
                                                                                                    	at android.content.ContextWrapper.getDir(ContextWrapper.java:351)
                                                                                                    	at com.clevertap.android.sdk.inapp.images.FileResourceProvider.<init>(FileResourceProvider.kt:57)
                                                                                                    	at com.clevertap.android.sdk.inapp.images.repo.FileResourcesRepoFactory$Companion.createFileResourcesRepo(FileResourcesRepoFactory.kt:45)
                                                                                                    	at com.clevertap.android.sdk.inapp.images.repo.FileResourcesRepoFactory.createFileResourcesRepo(Unknown Source:2)
                                                                                                    	at com.clevertap.android.sdk.CleverTapFactory.getCoreState(CleverTapFactory.java:178)
                                                                                                    	at com.clevertap.android.sdk.CleverTapAPI.<init>(CleverTapAPI.java:1164)
                                                                                                    	at com.clevertap.android.sdk.CleverTapAPI.instanceWithConfig(CleverTapAPI.java:886)
                                                                                                    	at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:751)
                                                                                                    	at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstance(CleverTapAPI.java:766)
                                                                                                    	at com.clevertap.android.sdk.CleverTapAPI.getDefaultInstanceOrFirstOther(CleverTapAPI.java:3063)
                                                                                                    	at com.clevertap.android.sdk.CleverTapAPI.createNotificationChannel(CleverTapAPI.java:315)
                                                                                                    	at com.viewlift.hoichoi.datasource.startup.CleverTapInitializer.initializeCleverTap(CleverTapInitializer.kt:27)
                                                                                                    	at com.viewlift.hoichoi.datasource.startup.CleverTapInitializer.create(CleverTapInitializer.kt:15)
                                                                                                    	at com.viewlift.hoichoi.datasource.startup.CleverTapInitializer.create(CleverTapInitializer.kt:11)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:138)
                                                                                                    	at androidx.startup.AppInitializer.initializeComponent(AppInitializer.java:117)
                                                                                                    	at com.viewlift.hoichoi.HoichoiApplication.onAppInitializer(HoichoiApplication.kt:72)
                                                                                                    	at com.viewlift.hoichoi.HoichoiApplication.onCreate(HoichoiApplication.kt:64)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by HGaurav328** [comment]
CleverTap version: com.clevertap.android:clevertap-android-sdk:7.0.1

**Comment by CTLalit** [comment]
We have recorded this as a part of our internal testing as well. Since this violation is related to just accessing file (rather just a directory reference) we will be solving this as it gets priorities in roadmap and mention it in release notes.

**Comment by wadva474** [comment]
We are experiencing this issue on SDK version 7.2.2, occurring during app startup and contributing to ANRs and frozen frames, impacting app stability and performance—please prioritize this in the roadmap. @CTLalit

**Comment by Anush-Shand** [comment]
This violation has been resolved in [v7.4.0](https://github.com/CleverTap/clevertap-android-sdk/releases/tag/corev7.4.0)
