### ISSUE TITLE
Getting Null Pointer Exception in Release Version

### ISSUE THREAD

**Issue by dhruvkaushal11** [CleverTap/clevertap-android-sdk#72]
Hi Team, 
I am getting Null Pointer Exception in Release Build on Native Android SDK

**Here are the Logs:**

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.toString()' on a null object reference
       at com.clevertap.android.sdk.DeviceInfo.fetchGoogleAdID(DeviceInfo.java:180)
       at com.clevertap.android.sdk.DeviceInfo.access$100(DeviceInfo.java:23)
       at com.clevertap.android.sdk.DeviceInfo$2.run(DeviceInfo.java:130)
       at java.lang.Thread.run(Thread.java:764)

**I am currently using:**
    implementation 'com.clevertap.android:clevertap-android-sdk:3.6.2'

**Comment by darshanclevertap** [comment]
@dhruvkaushal11 This was fixed in v3.6.3 but I'd suggest moving to the latest version v3.8.0 to be updated with the latest features and bug fixes. Thanks!
