### ISSUE TITLE
App crashing due to java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by ashwini009** [CleverTap/clevertap-android-sdk#8]
```
E/CleverTap: An exception occurred while trying to send the queue
                                                          java.net.SocketTimeoutException: timeout
                                                              at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:207)
                                                              at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                              at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                                              at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:919)
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:803)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:460)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:518)
                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
                                                              at com.clevertap.android.sdk.CommsManager.sendQueue(CommsManager.java:190)
                                                              at com.clevertap.android.sdk.CommsManager.flushDBQueue(CommsManager.java:104)
                                                              at com.clevertap.android.sdk.CommsManager.flushQueueSync(CommsManager.java:78)
                                                              at com.clevertap.android.sdk.CommsManager$1.run(CommsManager.java:57)
                                                              at com.clevertap.android.sdk.CleverTapAPI$1.run(CleverTapAPI.java:208)
                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                              at java.lang.Thread.run(Thread.java:818)
01-02 16:20:12.086 508-750/in.startv.hotstar E/Analytics: Error while uploading payloads
                                                          java.net.ConnectException: failed to connect to api.segment.io/34.214.37.134 (port 443) after 15000ms: isConnected failed: EHOSTUNREACH (No route to host)
                                                              at libcore.io.IoBridge.isConnected(IoBridge.java:257)
                                                              at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
                                                              at libcore.io.IoBridge.connect(IoBridge.java:127)
                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188)
                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:457)
                                                              at java.net.Socket.connect(Socket.java:927)
                                                              at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                                                              at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
                                                              at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
                                                              at com.android.okhttp.Connection.connect(Connection.java:167)
                                                              at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:209)
                                                              at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                              at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:353)
                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:342)
                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:260)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:454)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
                                                              at com.segment.analytics.Client.createPostConnection(Client.java:50)
                                                              at com.segment.analytics.Client.upload(Client.java:93)
                                                              at com.segment.analytics.SegmentIntegration.performFlush(SegmentIntegration.java:341)
                                                              at com.segment.analytics.SegmentIntegration$3.run(SegmentIntegration.java:319)
                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                              at java.lang.Thread.run(Thread.java:818)
                                                              at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:544)
                                                           Caused by: android.system.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
                                                              at libcore.io.IoBridge.isConnected(IoBridge.java:246)
                                                              at libcore.io.IoBridge.connectErrno(IoBridge.java:193) 
                                                              at libcore.io.IoBridge.connect(IoBridge.java:127) 
                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:188) 
                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:457) 
                                                              at java.net.Socket.connect(Socket.java:927) 
                                                              at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117) 
                                                              at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160) 
                                                              at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79) 
                                                              at com.android.okhttp.Connection.connect(Connection.java:167) 
                                                              at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:209) 
                                                              at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
                                                              at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:353) 
                                                              at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:342) 
                                                              at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:260) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:454) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114) 
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245) 
                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218) 
                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25) 
                                                              at com.segment.analytics.Client.createPostConnection(Client.java:50) 
                                                              at com.segment.analytics.Client.upload(Client.java:93) 
                                                              at com.segment.analytics.SegmentIntegration.performFlush(SegmentIntegration.java:341) 
                                                              at com.segment.analytics.SegmentIntegration$3.run(SegmentIntegration.java:319) 
                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                              at java.lang.Thread.run(Thread.java:818) 
                                                              at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:544) 
```

**Comment by darshanclevertap** [comment]
Hi @ashwini009, Could you please let us know which version of the SDK are you using, that would help us in resolving this faster?

**Comment by ashwini009** [comment]
@darshanclevertap We are using `3.1.4`

**Comment by darshanclevertap** [comment]
@ashwini009 Does this issue still persist on the newer versions? Or else I can close the issue?
