### ISSUE TITLE
Crash in CTFeatureFlagsController.java line 114

### ISSUE THREAD

**Issue by nabil6391** [CleverTap/clevertap-android-sdk#88]
Morning Guys,

Recently in our firebase crashlytics we came accoss this crash. The clevertap libary we are using is 3.8.0.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void c0.f.a.a.u2.d.a()' on a null object reference
       at com.clevertap.android.sdk.featureFlags.CTFeatureFlagsController$1.run(CTFeatureFlagsController.java:114)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7258)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`

Please have a look and let us know

**Comment by darshanclevertap** [comment]
Hi @nabil6391 

Thank you for bringing this to our notice. Can you let us know if this is reproducible on your end? Or does it only show up on Crashlytics? 
Also which Android OS versions and devices are affected and how much percentage?

Thanks!

**Comment by kumaratulismu** [comment]
@nabil6391 We have fixed this crash in v3.8.1.
Please update to the v3.8.1 and let us know if you still face this issue.

**Comment by nabil6391** [comment]
Thanks for the quick response guys.
