### ISSUE TITLE
Unable to support Android 11

### ISSUE THREAD

**Issue by alanlai1989** [CleverTap/clevertap-android-sdk#92]
Fatal Exception: java.lang.SecurityException: getDataNetworkTypeForSubscriber
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
       at android.os.Parcel.createException(Parcel.java:2357)
       at android.os.Parcel.readException(Parcel.java:2340)
       at android.os.Parcel.readException(Parcel.java:2282)
       at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8722)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2945)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2909)
       at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.getNetworkType(DeviceInfo.java:618)
       at com.clevertap.android.sdk.DeviceInfo$DeviceCachedInfo.<init>(DeviceInfo.java:546)
       at com.clevertap.android.sdk.DeviceInfo.getDeviceCachedInfo(DeviceInfo.java:81)
       at com.clevertap.android.sdk.DeviceInfo.access$000(DeviceInfo.java:23)
       at com.clevertap.android.sdk.DeviceInfo$1.run(DeviceInfo.java:52)
       at java.lang.Thread.run(Thread.java:923)

**Comment by kumaratulismu** [comment]
@alanlai1989 We have tried with the following config, it's working fine for us. Can you try with these config and let us know?

compileSdkVersion 30
buildToolsVersion '30.0.1'
targetSdkVersion 30

Clevertap sdk version - 3.8.2

Thanks

**Comment by kumaratulismu** [comment]
@alanlai1989 Are you still facing the issue? Please let us know.

**Comment by zomanubhav87** [comment]
It is still crashing

**Comment by alanlai1989** [comment]
@kumaratulismu It is still crashing with same error even i disabled 
`mCleverTapAPI.enableDeviceNetworkInfoReporting(false);`

**Comment by alanlai1989** [comment]
compileSdkVersion 29
buildToolsVersion '30.0.1'
targetSdkVersion 29

Clevertap sdk version - 3.8.2

It will work but this is not the premanent solution, the fix should come from clevertap sdk

**Comment by kumaratulismu** [comment]
@alanlai1989 Currently we support Android 9 only. We are going to support Android 10 next month. 

We don't support Android beta releases. We will look into this once Android 11 is released officially. 

Marking this as enhancement.

**Comment by kumaratulismu** [comment]
@alanlai1989 We will add a fix for this in our next planned release. Will keep you posted.

**Comment by Pro-55** [comment]
Android 11 is rolling out, when can we expect some fix for this?

**Comment by darshanclevertap** [comment]
@alanlai1989 @Pro-55 Are you asking for `READ_PHONE_STATE ` permission in your app?

**Comment by darshanclevertap** [comment]
@alanlai1989 We've fixed this in CleverTap Android SDK v3.9.1
