### ISSUE TITLE
NPE on Android 9

### ISSUE THREAD

**Issue by alanlai1989** [CleverTap/clevertap-android-sdk#93]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getBaseContext()' on a null object reference
       at com.clevertap.android.sdk.CTInAppBaseFullFragment.isTablet(CTInAppBaseFullFragment.java:20)
       at com.clevertap.android.sdk.CTInAppNativeInterstitialImageFragment$2.onGlobalLayout(CTInAppNativeInterstitialImageFragment.java:132)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:956)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2583)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
       at android.view.Choreographer.doCallbacks(Choreographer.java:893)
       at android.view.Choreographer.doFrame(Choreographer.java:812)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by piyush-kukadiya** [comment]
Thanks @alanlai1989 for reporting this.
Can you also share steps to reproduce this, that will be more helpful for us to debug and fix this.

**Comment by alanlai1989** [comment]
@piyush-kukadiya I cannot replicate this but from the log, it is related of checking device is tablet. From the data that collected, it is 100% Android 9 with Huawei such as Mate 10, Mate 20, Nova

**Comment by piyush-kukadiya** [comment]
Thanks @alanlai1989 Yes it is related to `isTablet` check, from the logs it's clear that `CTInAppBaseFullFragment ` is detached from `Activity` while calling `getBaseContext()` hence giving null. 
However to fix this we need to replicate and test. 
If you can share more info on this like full crash logs which includes your app's stack trace as well then that will be really helpful or any info like during device rotation or in background etc.

**Comment by alanlai1989** [comment]
@piyush-kukadiya I can't, I cannot replicate it. The crash was from firebase crashlytic. I can share the full stacktrace from firebase

**Comment by darshanclevertap** [comment]
@alanlai1989 Can you please share the details from firebase crashlytics?
