### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by prateekgupta22195** [CleverTap/clevertap-android-sdk#96]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.clevertap.android.sdk.CTInAppNotification.isPortrait()' on a null object reference
       at com.clevertap.android.sdk.InAppNotificationActivity.onCreate(InAppNotificationActivity.java:222)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by piyush-kukadiya** [comment]
Thanks @prateekgupta22195  for reporting. We will look into this and notify you once this fix is released. Meanwhile can you please share the steps to reproduce and full stack trace which includes your app as well?

**Comment by kumaratulismu** [comment]
@prateekgupta22195 We have fixed this issue. Will let you once we roll our next version.

**Comment by darshanclevertap** [comment]
This has been fixed in v3.9.0.
Please check and feel free to re-open the issue if you face any problem.
